# Generated by Django 5.1.5 on 2026-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_businesscard_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
