# Generated by Django 5.2.14 on 2026-05-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scanner",
            "0009_remove_knowledgerelationship_scanner_kno_relatio_9a2ce8_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_type", models.CharField(max_length=100)),
                ("evidence_id", models.PositiveIntegerField(blank=True, null=True)),
                ("evidence_excerpt", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="knowledgeentity",
            name="unique_knowledge_entity",
        ),
        migrations.RemoveIndex(
            model_name="knowledgeentity",
            name="scanner_kno_source__603194_idx",
        ),
        migrations.AddField(
            model_name="businesscard",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("investor", "Investor"),
                    ("partner", "Partner"),
                    ("research", "Research"),
                    ("mentor", "Mentor"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="extracted_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="raw_ai_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="normalized_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="canonical_name",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="source_table",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("merged", "Merged"),
                ],
                default="active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="source_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="knowledgerelationship",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("contact", "Contact"),
                    ("company", "Company"),
                    ("event", "Event"),
                    ("opportunity", "Opportunity"),
                    ("task", "Task"),
                    ("interaction", "Interaction"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("contact", "Contact"),
                    ("company", "Company"),
                    ("event", "Event"),
                    ("domain", "Domain"),
                    ("opportunity", "Opportunity"),
                    ("task", "Task"),
                    ("interaction", "Interaction"),
                    ("document", "Document"),
                    ("evidence", "Evidence"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgerelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("WORKS_AT", "Works At"),
                    ("MET_AT", "Met At"),
                    ("BELONGS_TO_DOMAIN", "Belongs To Domain"),
                    ("DISCUSSED_USE_CASE", "Discussed Use Case"),
                    ("LINKED_TO_OPPORTUNITY", "Linked To Opportunity"),
                    ("HAS_INTERACTION", "Has Interaction"),
                    ("HAS_TASK", "Has Task"),
                    ("ASSIGNED_TO", "Assigned To"),
                    ("DOCUMENT_SHARED_WITH", "Document Shared With"),
                    ("SOURCE_EVIDENCE_OF", "Source Evidence Of"),
                    ("SIMILAR_TO", "Similar To"),
                    ("DUPLICATE_CANDIDATE_OF", "Duplicate Candidate Of"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["normalized_name"], name="scanner_com_normali_4962cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["company_type"], name="scanner_com_company_863b01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(
                fields=["source_table", "source_id"],
                name="scanner_kno_source__a976b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(
                fields=["canonical_name"], name="scanner_kno_canonic_63e458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgerelationship",
            index=models.Index(
                fields=["relationship_type"], name="scanner_kno_relatio_9a2ce8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgerelationship",
            index=models.Index(
                fields=["source_entity", "relationship_type"],
                name="scanner_kno_source__a79a3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgerelationship",
            index=models.Index(
                fields=["target_entity", "relationship_type"],
                name="scanner_kno_target__aaabbd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeentity",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "source_table", "source_id"),
                name="unique_knowledge_entity",
            ),
        ),
        migrations.AddField(
            model_name="relationshipevidence",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_items",
                to="scanner.knowledgerelationship",
            ),
        ),
    ]
