# Generated by Django 5.1.5 on 2026-05-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_remove_opportunity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='relationship_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('dormant', 'Dormant')], default='prospect', max_length=20),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting')], max_length=20)),
                ('summary', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='scanner.businesscard')),
            ],
        ),
    ]
