# Generated by Django 5.1.5 on 2026-06-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_subscriptionplan_systemconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingprofile', to='scanner.subscriptionplan'),
        ),
    ]
